sigarLocation: /Users/christian/IdeaProjects/maintenance-server/target/lib
server:
  applicationConnectors:
    - type: http
      port: 8080
logging:
  level: INFO
  appenders:
       - type: console
         threshold: DEBUG