sigarLocation: /Users/christian/IdeaProjects/hwapi-server/target/lib
user:
  username: krillsson
  password: supersafepassword
server:
  applicationConnectors:
    - type: http
      port: 8080
logging:
  level: INFO
  appenders:
       - type: console
         threshold: DEBUG