#########################################
### System-Api configuration          ###
#########################################
user:
  username: user
  password: password
windows:
  enableOhmJniWrapper: true
#forwardHttps: false

#########################################
### Dropwizard specific configuration ###
#########################################
server:
  applicationContextPath: /v1
  applicationConnectors:
    - type: http
      port: 8080
logging:
  loggers:

    # Overrides the level of com.example.dw.Thing and sets it to DEBUG.
    "oshi": INFO
    "org.eclipse.jetty": INFO
  level: DEBUG
  appenders:
       - type: console
         threshold: DEBUG
# Disabled in the headless version
#       - type: textarea
#         threshold: DEBUG