#########################################
### System-Api configuration          ###
#########################################
user:
  username: user
  password: password
windows:
  enableOhmJniWrapper: true
#forwardHttps: false

#########################################
### Dropwizard specific configuration ###
#########################################
server:
  applicationContextPath: /v1
  applicationConnectors:
    - type: http
      port: 8080
logging:
  level: INFO
  appenders:
       - type: console
         threshold: DEBUG
# Disabled in the headless version
#       - type: textarea
#         threshold: DEBUG