user:
  username: user
  password: password
windows:
  enableOhmJniWrapper: false
server:
  applicationContextPath: /v1
  applicationConnectors:
    - type: http
      port: 8080
logging:
  level: INFO
  appenders:
       - type: console
         threshold: DEBUG