#########################################
### System-Api configuration          ###
#########################################
monitor:
  history:
    duration: 30
    unit: MINUTES
    purging:
      olderThan: 3
      unit: DAYS
      purgeEvery: 1
      purgeEveryUnit: DAYS
  cache:
    duration: 5
    unit: SECONDS
user:
  username: user
  password: password
windows:
  enableOhmJniWrapper: true
#forwardHttps: false

#########################################
### Dropwizard specific configuration ###
#########################################
server:
  maxThreads: 100
  minThreads: 1
  maxQueuedRequests: 100
  idleThreadTimeout: 1 minute
  applicationContextPath: /v1
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO

  # Logger-specific levels.
  loggers:
    # Enables the SQL query log and redirect it to a separate file
    "com.krillsson.sysapi":
      level: DEBUG
      appenders:
        - type: console